// convert_assets.dart
import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  final assetPath = p.join(Directory.current.path, 'assets', 'products.xlsx');
  final outputFile = p.join(Directory.current.path, 'lib', 'data', 'product_data.dart');

  final file = File(assetPath);
  if (!file.existsSync()) {
    print('Error: products.xlsx not found at $assetPath');
    return;
  }

  final bytes = file.readAsBytesSync();

  final buffer = StringBuffer();
  buffer.writeln('// This file is generated by convert_assets.dart. Do not edit manually.');
  buffer.writeln('import \'dart:typed_data\';');
  buffer.writeln('');
  buffer.writeln('final Uint8List productBytes = Uint8List.fromList([');
  buffer.writeln('  ${bytes.join(', ')}');
  buffer.writeln(']);');

  Directory(p.dirname(outputFile)).createSync(recursive: true);
  File(outputFile).writeAsStringSync(buffer.toString());

  print('Successfully converted products.xlsx to $outputFile');
}